### ISSUE TITLE
Can I add this to steppy/steppy-toolkit

### ISSUE THREAD

**Issue by jakubczakon** [pklauke/mlopt#1]
Hi I came across this repository and find this transformer quite usefull.
I am also one of the core developers of two projects:
* steppy https://github.com/neptune-ml/steppy
* steppy-toolkit https://github.com/neptune-ml/steppy-toolkit

where we are building a toolkit with a lot of stuff that you can use for efficient data-sciensing and kaggling.
Can I add this transformer to our library or better yet would you like to make a PR with this transformer to steppy-toolkig?

**Comment by pklauke** [comment]
Hi,

I like that idea. I will create a Pull Request.

Regards,
Peter
